language: bash
sudo: false
notifications:
  slack:
    rooms:
     - "vfnnrw:8Xxsz5koOsxIwN9zlLyIcL9"
    on_success: never
    on_failure: change
  email:
    on_success: change
    on_failure: always
script:
 - touch build_dryrun
 - ./build_gluon gluon08 nightly
